### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by epedagogue** [epedagogue/frontendEP#12]
Correct the spelling of Servies to "Services"

![Capture4](https://user-images.githubusercontent.com/81159997/122018343-640eec00-cde0-11eb-94e9-f9cb963de92b.PNG)

**Comment by lalitdeol** [comment]
I have resolved this issue

**Comment by lalitdeol** [comment]
<img width="945" alt="Screenshot 2021-06-15 152918" src="https://user-images.githubusercontent.com/65801802/122034908-9c69f680-cdef-11eb-96f1-02172b57ab72.png">


check the image i have resolved the issue
