### ISSUE TITLE
Services 

### ISSUE THREAD

**Issue by epedagogue** [epedagogue/frontendEP#16]
Make the services like this:- Study materials 

https://byjus.com/?utm_source=Google&utm_medium=CPC&utm_campaign=K12-Byjus-Brand-Desktop-India&utm_term=byju%27s&gclid=CjwKCAjwn6GGBhADEiwAruUcKsd3TJV24uZJbaIPq25b4r41IWnNwPx06yILkt7coWkJsheQBxckYBoC4X4QAvD_BwE

**Comment by lalitdeol** [comment]
this is not an issue
