### ISSUE TITLE
Fields are accepting wrong input in Contact section 

### ISSUE THREAD

**Issue by priyakundu22** [epedagogue/frontendEP#17]
**Environment**

 epedagogue - Frontend
Commit Id - 7d71e43dc59cd64178de6ebfc9d8e57cdbf1ad35
Mode - Production/Developer/Maintenance

**Description**

_Name field_ is accepting wrong input like numerical value.
_Email field_ is accepting inputs without a special character like @.

**Steps to reproduce**

- open Epedagogue
- navigate to contact 
- scroll down
- fill the Field _Name_ with integer and _Email_ with random value without @.
- Click on Submit content.

**Expected Result**

The error message should be displayed for the wrong input.

**Actual result**
These fields are accepting the wrong inputs.

![WhatsApp Image 2021-09-29 at 2 14 40 PM](https://user-images.githubusercontent.com/88392203/135236768-bc7fd8f0-3080-4371-9cbe-33768c383585.jpeg)

**Comment by lalitdeol** [comment]
issue fixed
