### ISSUE TITLE
User can submit comment without name/email field by inspecting it, in contact section

### ISSUE THREAD

**Issue by priyakundu22** [epedagogue/frontendEP#18]
**Environment**

epedagogue - Frontend
Commit Id - 7d71e43dc59cd64178de6ebfc9d8e57cdbf1ad35
Mode - Production/Developer/Maintenance

**Description**

The page is accepting the comment without name or email if a user deletes the field by inspecting it.

**Steps to reproduce**

- open Epedagogue
- navigate to contact
- scroll down 
- inspect it
- select name or email or both field
- delete
- cross the inspect 
- input something on write message
- click on submit comment

 
**Expected Result**

The comment should not be accepted because name and email field are mandatory. 

**Actual result**

These fields are accepting without name and email.
![Screenshot_1](https://user-images.githubusercontent.com/88392203/135239884-827b335c-3284-47a5-99c0-ada924bad2ae.png)

**Comment by lalitdeol** [comment]
issue fixed
