### ISSUE TITLE
User can't able to register as the Apply job button is not working in home page

### ISSUE THREAD

**Issue by priyakundu22** [epedagogue/frontendEP#19]
**Environment**

epedagogue - Frontend
Commit Id - 7d71e43dc59cd64178de6ebfc9d8e57cdbf1ad35
Mode - Production/Developer/Maintenance

**Description**

Apply button is not working in the registration form in the Home page.

**Steps to reproduce**

- open Epedagogue
- in this home page scroll down 
- in free demo section fill the registration form
- click on apply for it
-

**Expected Result**

Users must be able to apply it by clicking the button _Apply for it_.

**Actual result**

The button is not working.
![Screenshot_2](https://user-images.githubusercontent.com/88392203/135242483-d964acda-4440-4bf1-815a-6fbc33306396.png)

**Comment by lalitdeol** [comment]
issue fixed
