### ISSUE TITLE
Subscribe button isn't working in Home page

### ISSUE THREAD

**Issue by priyakundu22** [epedagogue/frontendEP#20]
**Environment**

epedagogue - Frontend
Commit Id - 7d71e43dc59cd64178de6ebfc9d8e57cdbf1ad35
Mode - Production/Developer/Maintenance

**Description**

Subscribe button is not working on the Home page.

**Steps to reproduce**

- open Epedagogue
- On this home page scroll down
- at the bottom fill the field of Subscribe 
- click on subscribe button

**Expected Result**

Users must be able to subscribe by clicking the button _subscribe_

**Actual result**

The button is not working.
![Screenshot_3](https://user-images.githubusercontent.com/88392203/135246645-5645008d-4bcb-4321-8e0d-9a1341eb686e.png)

**Comment by lalitdeol** [comment]
issue fixed
