### ISSUE TITLE
**Apply for it** button is not working

### ISSUE THREAD

**Issue by snehu123** [epedagogue/frontendEP#21]
## Environment

Epedagogue- version 1.0.0
Commit id- 7d71e43dc59cd64178de6ebfc9d8e57cdbf1ad35
Mode- Production/Developer/Maintenance

----------

## Description

-Only accept name, email and phone no.
-Do not accept comment.
-Didn't navigate to new page when click on **Apply for it**.

----------

## Steps to reproduce

-Hit this URL- https://www.epedagogue.com/#/
-Scroll down the page and enter the details in **Get Free Demo**.
-Click on **Apply for it** button.

-----------

## Expected Result

-Get access for free demo.

----------

## Actual Result

-Didn't get access for free demo and **Apply for it** button not working.

**Comment by lalitdeol** [comment]
issue fixted
