### ISSUE TITLE
'Learn More' button is not working

### ISSUE THREAD

**Issue by snehu123** [epedagogue/frontendEP#22]
## Environment

Epedagogue- version 1.0.0
Commit id- 7d71e43
Mode- Production/Developer/Maintenance

----------

## Description

-When click on **Learn More** not able to know about more informations.
-**Learn More** buttons are not working.

-----------

## Steps to reproduce

-Hit this URL- https://www.epedagogue.com/#/
-Scroll down the page and click on **Learn More** button.

-----------

## Expected Result

-User is able to know more details.

----------

## Actual Result

-User is not able to know more details.

-----------
![ep-learn-01](https://user-images.githubusercontent.com/88393197/135254979-1d130720-773d-47d7-bd4b-599268c0a227.png)
![ep-learn-02](https://user-images.githubusercontent.com/88393197/135255015-e174c82c-dd5e-4f6f-a7ad-ca0aa2191de7.png)
![ep-learn-03](https://user-images.githubusercontent.com/88393197/135255026-6cd85321-eb50-42b6-920a-746f12bc4094.png)

**Comment by lalitdeol** [comment]
bug fixed
