### ISSUE TITLE
No description is available for Performance Testing'

### ISSUE THREAD

**Issue by snehu123** [epedagogue/frontendEP#23]
## Environment

Epedagogue- version 1.0.0
Commit id- 7d71e43
Mode- Production/Developer/Maintenance

-----------

## Description

-User want to know about more on **Performance Testing**.
-No details and information shown.

----------

## Steps to Reproduce

-Hit this URL- https://www.epedagogue.com/#/
-Navigate to **Courses** > **Software Testing Training** > **Performance Testing**

----------

## Expected Result

-**Performance Testing** details shown.

----------

## Actual Result

-No details shown.

----------

**Comment by lalitdeol** [comment]
issue fixed
