### ISSUE TITLE
Change the background or change the font color at home page in a particular section 

### ISSUE THREAD

**Issue by priyakundu22** [epedagogue/frontendEP#24]
**Environment**

epedagogue - Frontend
Commit Id - 7d71e43dc59cd64178de6ebfc9d8e57cdbf1ad35
Mode - Production/Developer/Maintenance

**Description**

some specific attributes are not clearly visible for the background and font color. 

**Steps to reproduce**

- open Epedagogue
- On this home page scroll down

**Expected Result**

Users must be able to see the attributes clearly

**Actual result**

Not clearly visible & after navigating those attributes the font color(orange) is also not soothing for the user. 
![Screenshot_4](https://user-images.githubusercontent.com/88392203/135258769-f8a46eb5-1eaa-4adc-a973-fe25068f6b15.png)

**Comment by lalitdeol** [comment]
issue solved

**Comment by lalitdeol** [comment]
bug fixed
