### ISSUE TITLE
Add greeting text and heading to My team page 

### ISSUE THREAD

**Issue by epedagogue** [epedagogue/frontendEP#7]
## Greeting Introductory text- 
The importance of teamwork in the workplace is demonstrated by the feelings of unity, collaboration, and motivation that it brings. An effective team works as a collective unit by utilizing the skills and talents of each team member to support and achieve a common goal.
In simple terms, teamwork is when a group of people combines individual skill sets to produce amazing outcomes.
Look back at some of the greatest things accomplished, and you’ll find that a good team was behind it. Lets meet our highly qualified team.

## Heading 
**Our Team**

**Comment by lalitdeol** [comment]
done
